{% set version = "2.0.0" %}
{% set name = "pling" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/iqbal-lab-org/{{ name|lower }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5d52b40d5ad764da9c7f427a4f28b5853f47ec6e55c86745952e2a6e6e0dccc8

build:
  number: 0
  noarch: python
  script: "pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - pling = pling.__main__:main
  run_exports:
    - {{ pin_subpackage("pling", max_pin="x") }}

requirements:
  run:
    - python >=3.9,<3.12
    - sourmash >=4.4.0,<5.0.0
    - pandas >=1.5.3
    - numpy >=1.26.0
    - intervaltree >=3.0.2
    - mummer >=3.23
    - glpk >=5.0
    - gurobi 10.0.1
    - snakemake >=7.25.4,<8.0.0
    - plasnet >=0.6.0
    - dingII
test:
  imports:
    - pling

  commands:
    - pling --help

about:
  home: https://github.com/iqbal-lab-org/pling
  license: LICENSE
  license_family: MIT
  summary: 'Pling computes the rearrangement distance between plasmids and clusters on their basis '

